id = "text-language-server"
name = "Text Language Server"
version = "0.0.1"
schema_version = 1
authors = ["Adam Yu <adamxhy123@gmail.com>"]
description = "Common text utilities provided by text-language-server"
repository = "https://github.com/Lev1ty/zed-text-utility"

[language_servers.text-language-server]
name = "Text Language Server"
languages = [
  "Ansible",
  "AsciiDoc",
  "Astro",
  "Bash",
  "Biome",
  "C",
  "C++",
  "C#",
  "Clojure",
  "CSS",
  "Dart",
  "Deno",
  "Docker",
  "Elixir",
  "Elm",
  "Emmet",
  "Erlang",
  "Fish",
  "GDScript",
  "Gleam",
  "GLSL",
  "Go",
  "Groovy",
  "Haskell",
  "Helm",
  "HTML",
  "Java",
  "JavaScript",
  "Julia",
  "JSON",
  "Jsonnet",
  "Kotlin",
  "Lua",
  "Luau",
  "Makefile",
  "Markdown",
  "Nim",
  "OCaml",
  "PHP",
  "Plain Text",
  "Prisma",
  "Proto",
  "PureScript",
  "Python",
  "R",
  "Rego",
  "ReStructuredText",
  "Racket",
  "Roc",
  "Ruby",
  "Rust",
  "Scala",
  "Scheme",
  "Shell Script",
  "Svelte",
  "Swift",
  "Tailwind CSS",
  "Terraform",
  "TOML",
  "TypeScript",
  "Uiua",
  "Vue",
  "XML",
  "YAML",
  "Yarn",
  "Zig",
]
